# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_hclust_cpp <- function(dist_matrix, method) {
    .Call(`_FastHierarchicalClust_fast_hclust_cpp`, dist_matrix, method)
}

naive_hclust_cpp <- function(dist_matrix, method) {
    .Call(`_FastHierarchicalClust_naive_hclust_cpp`, dist_matrix, method)
}

rcpp_hello_world <- function() {
    .Call(`_FastHierarchicalClust_rcpp_hello_world`)
}

